### ISSUE TITLE
register for user

### ISSUE THREAD

**Issue by AIbnuHIbban** [munza/lumen-api-starter#10]
is there no route for the register user that generated the JWT Token ?? I do not find it

**Comment by munza** [comment]
I am sorry that there was no obvious instruction for user authentication in the readme. I should just add that or you can add that and create a PR if you want :)

Here is the instruction to get a token for a registered user.

```
curl --location --request POST 'http://127.0.0.1:8000/auth' \
--header 'Content-Type: application/json' \
--data-raw '{
	"email": "user@localtest.me",
	"password": "password"
}'
```

And to create a user -
- Run `docker-compose exec app php artisan ti` to start the Laravel Tinker console.
- Run `App\Models\User::factory()->create(['email'=>'user@localtest.me']);` to create a user. (Default password in `password`).

**Comment by munza** [comment]
@AIbnuHIbban let me know if you are interested to add the authentication instruction. Otherwise, I will add it tomorrow :)

**Comment by munza** [comment]
An issue has been created for authentication insturction #11

**Comment by AIbnuHIbban** [comment]
Oh, my bad .. 
Thanks for information..
